(function(){var aa=typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},n=ca(this),p=function(a,b){if(b)a:{var c=n;a=a.split(".");for(var e=0;e<a.length-1;e++){var g=a[e];if(!(g in c))break a;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}},q;if(typeof Object.setPrototypeOf=="function")q=Object.setPrototypeOf;else{var t;a:{var da={a:!0},u={};try{u.__proto__=da;t=u.a;break a}catch(a){}t=!1}q=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var v=q,w=function(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(v)v(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.oa=b.prototype},ea=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},x=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ea(a)};
throw Error(String(a)+" is not an iterable or ArrayLike");},z=function(a){return y(a,a)},y=function(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a},fa=function(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b};p("globalThis",function(a){return a||n});
p("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof g?d:new g(function(f){f(d)})}if(a)return a;b.prototype.i=function(d){if(this.g==null){this.g=[];var f=this;this.j(function(){f.o()})}this.g.push(d)};var e=n.setTimeout;b.prototype.j=function(d){e(d,0)};b.prototype.o=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(k){this.l(k)}}}this.g=null};b.prototype.l=function(d){this.j(function(){throw d;
})};var g=function(d){this.i=0;this.j=void 0;this.g=[];this.O=!1;var f=this.l();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};g.prototype.l=function(){function d(k){return function(l){h||(h=!0,k.call(f,l))}}var f=this,h=!1;return{resolve:d(this.ha),reject:d(this.o)}};g.prototype.ha=function(d){if(d===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof g)this.ma(d);else{a:switch(typeof d){case "object":var f=d!=null;break a;case "function":f=!0;break a;default:f=
!1}f?this.W(d):this.N(d)}};g.prototype.W=function(d){var f=void 0;try{f=d.then}catch(h){this.o(h);return}typeof f=="function"?this.na(f,d):this.N(d)};g.prototype.o=function(d){this.H(2,d)};g.prototype.N=function(d){this.H(1,d)};g.prototype.H=function(d,f){if(this.i!=0)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.i);this.i=d;this.j=f;this.i===2&&this.ka();this.U()};g.prototype.ka=function(){var d=this;e(function(){if(d.V()){var f=n.console;typeof f!=="undefined"&&
f.error(d.j)}},1)};g.prototype.V=function(){if(this.O)return!1;var d=n.CustomEvent,f=n.Event,h=n.dispatchEvent;if(typeof h==="undefined")return!0;typeof d==="function"?d=new d("unhandledrejection",{cancelable:!0}):typeof f==="function"?d=new f("unhandledrejection",{cancelable:!0}):(d=n.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.j;return h(d)};g.prototype.U=function(){if(this.g!=null){for(var d=0;d<this.g.length;++d)D.i(this.g[d]);
this.g=null}};var D=new b;g.prototype.ma=function(d){var f=this.l();d.u(f.resolve,f.reject)};g.prototype.na=function(d,f){var h=this.l();try{d.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};g.prototype.then=function(d,f){function h(m,r){return typeof m=="function"?function(E){try{k(m(E))}catch(F){l(F)}}:r}var k,l,G=new g(function(m,r){k=m;l=r});this.u(h(d,k),h(f,l));return G};g.prototype.catch=function(d){return this.then(void 0,d)};g.prototype.u=function(d,f){function h(){switch(k.i){case 1:d(k.j);
break;case 2:f(k.j);break;default:throw Error("Unexpected state: "+k.i);}}var k=this;this.g==null?D.i(h):this.g.push(h);this.O=!0};g.resolve=c;g.reject=function(d){return new g(function(f,h){h(d)})};g.race=function(d){return new g(function(f,h){for(var k=x(d),l=k.next();!l.done;l=k.next())c(l.value).u(f,h)})};g.all=function(d){var f=x(d),h=f.next();return h.done?c([]):new g(function(k,l){function G(E){return function(F){m[E]=F;r--;r==0&&k(m)}}var m=[],r=0;do m.push(void 0),r++,c(h.value).u(G(m.length-
1),l),h=f.next();while(!h.done)})};return g});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A=function(a,b){function c(){}c.prototype=b.prototype;a.oa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qa=function(e,g,D){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[g].apply(e,d)}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var B={};function C(){if(B!==B)throw Error("Bad secret");};var H=globalThis.trustedTypes,I;function ha(){var a=null;if(!H)return a;try{var b=function(c){return c};a=H.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){throw c;}return a};var J=function(a){C();this.g=a};J.prototype.toString=function(){return this.g+""};function K(a){var b;I===void 0&&(I=ha());a=(b=I)?b.createScriptURL(a):a;return new J(a)};var L=function(a){C();this.g=a};L.prototype.toString=function(){return this.g};new L("about:blank");new L("about:invalid#zClosurez");var M=function(a){this.g=a};function N(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,N);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}A(N,Error);N.prototype.name="CustomError";function O(a,b){a=a.split("%s");for(var c="",e=a.length-1,g=0;g<e;g++)c+=a[g]+(g<b.length?b[g]:"%s");N.call(this,c+a[e])}A(O,N);O.prototype.name="AssertionError";var P=function(a,b,c){if(!a){var e="Assertion failed";if(b){e+=": "+b;var g=Array.prototype.slice.call(arguments,2)}throw new O(""+e,g||[]);}};var ia="closure_listenable_"+(Math.random()*1E6|0);var Q=function(a){this.g=a};w(Q,M);Q.prototype[ia]=!0;var R=function(a){this.g=a};w(R,Q);var S=function(a,b){this.g=a;this.i=b||null};w(S,M);S.prototype.then=function(a,b,c){var e;a&&(e=ja(this,a));this.g.aa(e,b,c)};var T=function(a){return new Promise(function(b,c){a.then(b,c)})},ja=function(a,b){var c=a.i;return c?function(e){b.call(this,new c(e))}:b};var ka=[];var U=function(a){this.g=a||gbar.a;this.j=this.i=null};w(U,M);var la=function(){P(!Object.isSealed(U),"Cannot use getInstance() with a sealed constructor.");var a="v";if(U.v&&U.hasOwnProperty(a))a=U.v;else{ka.push(U);var b=new U;U.v=b;P(U.hasOwnProperty(a),"Could not instantiate singleton.");a=b}return a},ma=function(){return new Promise(function(a){window.gbar||(window.gbar={});if(window.gbar.a)return a(la());(new Promise(function(b){window.gbar.ap=b})).then(function(){return a(la())})})};var na=z([""]),oa=y(["\x00"],["\\0"]),pa=y(["\n"],["\\n"]),qa=y(["\x00"],["\\u0000"]),ra=z([""]),sa=y(["\x00"],["\\0"]),ta=y(["\n"],["\\n"]),ua=y(["\x00"],["\\u0000"]);function V(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function W(a){return a.toString().indexOf("`")===-1}var va=W(function(a){return a(na)})||W(function(a){return a(oa)})||W(function(a){return a(pa)})||W(function(a){return a(qa)}),wa=V(ra)&&V(sa)&&V(ta)&&V(ua);var xa=[],ya=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};xa.indexOf(ya)===-1&&xa.push(ya);var za=z(["https://accounts.google.com/gsi/client"]);function Aa(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");Ba?(Ca=!0,Da&&X()):X()}
var X,Y=null,Z=window,Ea=Z.colabExperiments&&Z.colabExperiments.first_party_auth,Ba=!Ea,Da=!1,Ca=!1,Fa=document.getElementsByTagName("script")[0],Ga=function(a){var b=fa.apply(1,arguments);if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!va&&a===a.raw||!(va&&!wa||V(a))||b.length+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");
if(b.length===0)return K(a[0]);var c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var e=c.indexOf("//")+2;var g=c.indexOf("/",e);if(g<=e)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");e=c.substring(e,g);if(!/^[0-9a-z.:-]+$/i.test(e))throw Error("The origin contains unsupported characters.");if(!/^[^:]*(:[0-9]+)?$/i.test(e))throw Error("Invalid port number.");
if(!/(^|\.)[a-z][^.]*$/i.test(e))throw Error("The top-level domain must start with a letter.");e=!0}else e=!1;if(!e)if(/^\//.test(c))if(c==="/"||c.length>1&&c[1]!=="/"&&c[1]!=="\\")e=!0;else throw Error("The path start in the url is invalid.");else e=!1;if(!(e=e||RegExp("^[^:\\s\\\\/]+/").test(c)))if(/^about:blank/.test(c)){if(c!=="about:blank"&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");e=!0}else e=!1;if(!e)throw Error("Trying to interpolate expressions in an unsupported url format.");
c=a[0];for(e=0;e<b.length;e++)c+=encodeURIComponent(b[e])+a[e+1];return K(c)}(za);
function Ha(){if(Y)return Y;window.performance.mark("gapi_load_start");return Y=new Promise(function(a,b){X=a;Ba&&Ia(function(){b(Error("Error loading "+Ga))});if(Ea&&typeof gbar!=="undefined")ma().then(function(e){e.j||(e.j=new S(e.g.bh()));return T(e.j)}).then(function(){gapi.load("client",Aa)}),ma().then(function(e){e.i||(e.i=new S(e.g.bf(),R));return T(e.i)}).then(function(e){var g=document.documentElement.getAttribute("theme")==="dark";g&&(e.g.pp(g),e.g.pd("transparent"))});else{Z.gapi_onload=
Aa;var c=K("https://apis.google.com/js/client.js");Ja({src:c,onerror:function(){b(Error("Error loading "+c))}})}})}function Ia(a){Ja({src:Ga,onload:function(){Da=!0;Ca&&X()},onerror:a})}
function Ja(a){var b=document;var c="SCRIPT";b.contentType==="application/xhtml+xml"&&(c=c.toLowerCase());c=b.createElement(c);b=a.src;if(b instanceof J)b=b.g;else throw Error("Unexpected type when unwrapping TrustedResourceUrl");c.src=b;var e;b=c.ownerDocument;b=b===void 0?document:b;var g;b=(g=(e=b).querySelector)==null?void 0:g.call(e,"script[nonce]");(e=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&c.setAttribute("nonce",e);c.async=!0;a.onload&&(c.onload=a.onload);a.onerror&&(c.onerror=a.onerror);
Fa.parentNode.insertBefore(c,Fa)}Z.colab_gapi_loader={load:Ha};Ha().then(function(){},function(){});}).call(this);
